.TH "src/ds.hpp" 3 "PK3 Logger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ds.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <iostream>\fP
.br
\fR#include <memory>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmyds::CustomVector< T >\fP"
.br
.RI "Własna implementacja wektora z biblioteki STL\&. "
.ti -1c
.RI "class \fBmyds::CustomVector< T >::Iterator\fP"
.br
.RI "Własna implementacja iteratora do struktury \fBCustomVector\fP\&. Służy nam do łatwego dostępu do danych\&. "
.ti -1c
.RI "class \fBmyds::LinkedList< T >\fP"
.br
.RI "Własna implementacja listy jednokierunkowej\&. To kontener LIFO (Last in first out)\&. "
.ti -1c
.RI "class \fBmyds::LinkedList< T >::Iterator\fP"
.br
.RI "Własna implementacja iteratora do struktury \fBLinkedList\fP\&. Służy nam do łatwego dostępu do danych\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmyds\fP"
.br
.RI "Przestrzeń nazw przechowywująca własnoręcznie napisane kontenery\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PK3 Logger from the source code\&.
