.TH "src/main.cpp" 3 "PK3 Logger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <iostream>\fP
.br
\fR#include <sstream>\fP
.br
\fR#include 'ds\&.hpp'\fP
.br
\fR#include 'log\&.hpp'\fP
.br
\fR#include 'ui\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.RI "Punkt wejściowy do programu\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Punkt wejściowy do programu\&. 
.PP
\fBReturns\fP
.RS 4
0, jeśli program wykonał się poprawnie\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for PK3 Logger from the source code\&.
