.TH "myds" 3 "PK3 Logger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
myds \- Przestrzeń nazw przechowywująca własnoręcznie napisane kontenery\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCustomVector\fP"
.br
.RI "Własna implementacja wektora z biblioteki STL\&. "
.ti -1c
.RI "class \fBLinkedList\fP"
.br
.RI "Własna implementacja listy jednokierunkowej\&. To kontener LIFO (Last in first out)\&. "
.in -1c
.SH "Detailed Description"
.PP 
Przestrzeń nazw przechowywująca własnoręcznie napisane kontenery\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for PK3 Logger from the source code\&.
